############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret timezone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

http:
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: home.garincha.com:8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

history:
  include:
    domains:
      - switch
    entities:
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_temperature
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_relative_humidity
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_temperature_2
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_relative_humidity_2
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_temperature_3
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_relative_humidity_3
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_temperature_4
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_relative_humidity_4
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_temperature_5
      - sensor.philio_technology_corporation_phpat02beu_multisensor_2in1_relative_humidity_5

#logger:
#  default: debug
#logger:
#  default: critical
#  logs:
#    homeassistant.components.http: warning

# Enables the frontend
frontend:

# Enables configuration UI
config:

hassio:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

recorder:
  purge_interval: 1
  purge_keep_days: 15

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Track the sun
sun:

zwave:
  usb_path: /dev/ttyAMA0
  network_key: !secret zwave_network_key

###########################################################
#
# Includes
#
############################################################

# Single Files

device_tracker: !include includes/device_trackers.yaml
script: !include scripts.yaml
weather: !include weather.yaml


# Merge List

automation: !include_dir_merge_list automations
sensor: !include_dir_merge_list sensors


# Merge Named

group: !include_dir_merge_named groups
panel_iframe: !include_dir_merge_named panel_iframe/
shell_command: !include_dir_merge_named shell_commands/

