- alias: 'Battery Alert'
  trigger:
    - platform: time
      at: '12:00:00'
  condition:
    condition: template
    value_template: "{% if states('sensor.low_battery') %}{{ true }}{% else %}{{ false }}{% endif %}"
  action:
    service: persistent_notification.create
    data_template:
      title: 'Low Battery levels'
      message: "{{ states('sensor.low_battery') }}"
      notification_id: low-battery-alert

