- platform: yr
  name: Weather
  monitored_conditions:
  - cloudiness
  - dewpointTemperature
  - fog
  - humidity
  - lowClouds
  - mediumClouds
  - highClouds
  - precipitation
  - pressure
  - symbol
  - temperature
  - windDirection
  - windSpeed