- platform: yweather
  name: yw_0
  monitored_conditions:
  - weather
  - weather_current
  - temp_min
  - temp_max
  - wind_speed
  - pressure
  - visibility
  - humidity
  - temperature
- platform: yweather
  name: yw_1
  forcecast: 1
  monitored_conditions:
  - weather
  - temp_min
  - temp_max
- platform: yweather
  woeid: !secret yweather_woeid
  name: yw_2
  forcecast: 2
  monitored_conditions:
  - weather
  - temp_min
  - temp_max
- platform: yweather
  woeid: !secret yweather_woeid
  forcecast: 3
  name: yw_3
  monitored_conditions:
  - weather
  - temp_min
  - temp_max
- platform: yweather
  name: yw_4
  forcecast: 4
  monitored_conditions:
  - weather
  - temp_min
  - temp_max
- platform: yweather
  name: yw_5
  forcecast: 5
  monitored_conditions:
  - weather
  - temp_min
  - temp_max